### ISSUE TITLE
Debounce time change not saving

### ISSUE THREAD

**Issue by EpicLemon99** [korkje/mow#3] opened 2022-03-18 18:21 UTC
Whenever I try to change the debounce time to something like 0ms or 2ms it just doesn't change. The CPS caps at 10cps, and by downloading Glorious Core on another computer I saw that the debounce time was still set to 10ms.

**Comment by korkje** [comment] 2022-03-19 13:40
That's strange, I'll look into it, maybe I messed up somewhere. But max cps for 10ms debounce should be 100, not 10? Anyway, Glorious Core does not actually read any info from the device other than the active profile id and battery status, so you wouldn't see a change there. When plugging into a machine that has Glorious Core open, it will just immediately load your device up with either default settings, or your settings from when you last connected to it.

**Comment by EpicLemon99** [comment] 2022-03-19 15:58
But if the Model O has onboard memory shouldn't the debounce time save even when changing it from Glorious Core?

**Comment by korkje** [comment] 2022-03-19 16:05
Yes, setting the debounce time from Glorious Core should work in the exact same way as setting it from this tool.

**Comment by korkje** [comment] 2022-03-19 16:11
What I mean is that when you set debounce time to 0-16 ms with this tool, you can't use Glorious Core to verify whether it worked, because Glorious Core only "knows" about configuration done with it.

**Comment by korkje** [comment] 2022-03-19 16:16
So I guess I am wondering why you suspected it isn't saving, as the 0-16ms range shouldn't have any effect on your cps anyway, as the max cps even for 16ms would be 62.5 (1s divided by 16ms) which I suspect is well beyond what any human is capable of. Was it only because Glorious Core shows 10ms, or do you have another way of verifying?

**Comment by korkje** [comment] 2022-03-19 16:49
How I understand it, a debounce time setting with such a low range is only suited for removing *unwanted* double clicks, like when you tap hard and fast far back on the clicker, and the vibration of it causes a second click. You know what I mean? It shouldn't have any bearing on your ability to click fast, unless you are actually *using* that phenomenon I just described in games, which would be awesome by the way.

I just managed to (a bit unscientifically, I'll concede) verify that the debounce setting *does* work for this, by reliably causing such double clicks by bumping my phone at the clicker on a specific angle, and repeating this for different settings. This seemed to quite reliably cause double clicks with the setting in the 0-4ms range, but not in the 10-16ms range. In between was a bit of a toss-up.

**Comment by korkje** [comment] 2022-03-19 16:56
And I also tried to set higher to values around 200ms by changing the allowed range in the tool, just to see if I was able to affect my ability to double click regularly (around 100-150ms between clicks for me). That did not work, but I suspect the device might internally enforce a cap of 16ms, ignore values that are higher, substitute a default (e.g. 10ms) when values are out of range etc.

**Comment by EpicLemon99** [comment] 2022-03-19 17:45
Other people can reach 25cps using butterfly clicking with this mouse but to do that you need to set your debounce time to 0ms-4ms. You also need to click the mouse in a certain way to make it double click but I think this also only works with a low debounce time.

**Comment by korkje** [comment] 2022-03-19 18:08
Aha, so that's actually a thing, I had no idea. I don't know why you would need <4ms debounce for 25cps though, as you would be clicking on average every 40ms. Maybe a subset of the clicks would be close enough to be affected by the debounce setting I guess, depending on technique. But regarding this issue, do you have a way for me to reproduce a problem if there is one?

**Comment by korkje** [comment] 2022-03-19 18:33
Did some reading up on the technique you mentioned, and it seems to rely on the double click phenomenon I described earlier. I tried my luck at some butterfly clicking on [this test page](https://codepen.io/blink172/pen/vERyxK), and managed to get a whole lot of double clicks with debounce <4ms, and almost none with >10ms. So I don't think there is a problem with this tool, do you agree?

**Comment by korkje** [comment] 2022-03-19 18:37
I should mention that debounce setting `mow config debounce` accepts an optional `--profile <profile-number>`, or it will default to profile 1, maybe you've been setting debounce on another profile than the one your using?

**Comment by korkje** [comment] 2022-03-19 18:43
I know it's a bit confusing how some settings affect the current profile (led brightness, lift-off distance, polling rate off the top of my head), while others affect the specified one or defaults to profile 1, but that's just the way the device is made. Glorious Core sort of gets around this issue by keeping an internal copy of the settings of the mouse, as well as listening for profile switching (the mouse reports this over one of the HID interfaces), which is a bit beyond the scope of a simple CLI tool like this one.

**Comment by EpicLemon99** [comment] 2022-03-19 19:57
How would I make the double click test code work?

**Comment by korkje** [comment] 2022-03-19 20:10
Just go to the website, click away at the yellow area (actually, looks like it registers clicks anywhere) and watch the counter labeled "Fast double click count". Actually, that counter is incremented every time two clicks are registered less than 0.08s (80ms) by default, so change that value in the JS code to 0.01 so it only increments for clicks 10ms apart.

When butterfly clicking in just the right way, you should be able to make the mouse double click some of the time, as long as you have a low enough debounce setting of e.g. 0ms. And if you change the setting to 10ms, the test page should by definition never register clicks that are less than 10ms apart, becaus that's what the debounce setting is supposed to prevent.

**Comment by korkje** [comment] 2022-03-19 20:25
Here's another [double click test](https://cps-check.com/double-click-test) site, this one supports changing double click time in a more friendly way. First set the double click time down to 0.01s. Then, try butterfly clicking for a while (make sure to click pretty far back, this makes the double clicks more likely) with the debounce setting at 0ms. You should be able to register double clicks quite often. Then, try changing the debounce setting to 10ms, and you should no longer be able to register double clicks. I tried on this site too myself, and everything works as expected.

**Comment by EpicLemon99** [comment] 2022-03-19 21:11
Not getting a single double click registered. I can clearly hear the difference between the normal clicks and the double clicks but they're not registering.

**Comment by korkje** [comment] 2022-03-19 21:34
And that's with 0ms debounce set for the profile you're using? Weird, is it the same when you use Glorious Core? Maybe it's a device firmware thing, I've read somewhere that there used to be a bug where double clicks would never register.

**Comment by EpicLemon99** [comment] 2022-03-20 12:35
The tool does actually work. I tried the 16ms debounce time and the most I could get was 7-8cps. So I think this is just a me issue. Using Glorious Core yields me the same results. I can however register double clicks on other sites than the one you linked, but it's very inconsistent.

**Comment by korkje** [comment] 2022-03-20 12:57
Allright, I'll close the issue then. Thanks for the feedback anyway, I learned something new! 👍

**Closed** 2022-03-20 12:57 UTC
